<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #111;
            margin: 0;
            padding: 0;
        }

        .header {
            border-bottom: 2px solid #111;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .title {
            font-size: 20px;
            font-weight: bold;
        }

        .meta {
            font-size: 11px;
            color: #555;
        }

        .section {
            margin-bottom: 18px;
        }

        .section h2 {
            font-size: 14px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 4px;
        }

        .box {
            padding: 10px;
            border: 1px solid #eee;
            background: #fafafa;
        }

        .footer {
            position: fixed;
            bottom: 0;
            font-size: 10px;
            text-align: center;
            width: 100%;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
    </style>
</head>

<body>

<div class="header">
    <div class="title">ILANDS AI Financial Report</div>
    <div class="meta">
        Generated by Ilands AI • {{ $report['generated_at'] }} • Report #{{ $report['id'] }}
    </div>
</div>

<div class="section">
    <h2>Executive Summary</h2>
    <div class="box">
        {{ $report['summary'] }}
    </div>
</div>

<div class="section">
    <h2>Full Report</h2>
    <div class="box">
        {{ $report['content'] }}
    </div>
</div>

<div class="section">
    <h2>AI Confidence</h2>
    <div class="box">
        {{ $report['confidence'] ?? 'N/A' }}%
    </div>
</div>

<div class="footer">
    Generated by Ilands AI • Confidential Financial Document
</div>

</body>
</html>